version: '3.8'

networks:
  lab_04:

services:
  redis:
    image: redis:7.2.3
    restart: always
    networks:
      - lab_04

  redis-commander:
    image: rediscommander/redis-commander
    platform: linux/amd64
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - '8081:8081'
    networks:
      - lab_04